project:
  type: book

book:
  title: "Git and GitHub Starter Guide"
  author: "Dom Skinnion"
  date: "last-modified"
  page-navigation: true
  search: true
  favicon: images/favicon.png
  chapters:
    - index.qmd
    - introduction.qmd
    - part: "Getting Started with Git and GitHub"
      chapters:
        - install_git.qmd
        - sign_up.qmd
        - create_repo.qmd
        - clone_repo.qmd
        - auth.qmd
    - part: "Editing Existing Repositories"
      chapters:
        - editing.qmd
        - command_line.qmd
    - part: "Resources"
      chapters:
        - resources.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
    code-link: true
    callout-appearance: simple

execute:
  freeze: auto

